runtime: java
env: flex
service: backend
runtime_config:
  jdk: openjdk8
handlers:
- url: /.*
  script: this field is required, but ignored
beta_settings:
  cloud_sql_instances: wise-isotope-255311:australia-southeast1:septdb
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
 
