runtime: python27
api_version: '1'
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: /
    application_readable: false
    static_files: build/index.html
    require_matching_file: false
    upload: build/index.html
  - url: /(.*)
    application_readable: false
    static_files: build/\1
    require_matching_file: false
    upload: build/.*
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
network: {}
